# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file New-Java-proj-Workflow/onlinebookstore-J2EE/pom.xml
      
    - name: Create Release
      id: create_release
      uses: action/create-release@v1
      with:
       tag_name: ${{ github.run_id }}
       release_name: ${{ github.run_id }}
       draft: false
       prerelease: false 
       
    - name: Upload Release 
      id: Upload_release
      uses: action/upload-release-asset@v1
      with:
        upload_url: $ {{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifact.zip
        asset_name: artifact.zip
        assest_content_type: application/zip
  

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
