name: SonarQube Scan

on:
  push:
    branches:
      - main # Change this to match your main branch name

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up SonarQube Container
        run: |
          docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
          sleep 30
        ports:
          - 9000:9000

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Use the desired Java version

      - name: SonarQube Scan
        run: |
          # Perform any necessary build steps here
          # Example: mvn clean install
          # Example: ./gradlew build
          mvn -f New-Java-proj-Workflow/onlinebookstore-J2EE/pom.xml sonar:sonar \
            -Dsonar.projectKey=New-Java-Proj  \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=admin \
            -Dsonar.password=admin1
        continue-on-error: true

      - name: Stop SonarQube Container
        run: docker stop sonarqube
